"""strategy library and defense engine

Revision ID: a957c6dc54e6
Revises: ba2d83aa362d
Create Date: 2026-09-06 04:39:12.217822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a957c6dc54e6'
down_revision: Union[str, Sequence[str], None] = 'ba2d83aa362d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_strategy_families',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_strategy_families_key'), 'campaign_strategy_families', ['key'], unique=True)
    op.create_table('campaign_strategy_types',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('secondary_family_keys', sa.JSON(), nullable=False),
    sa.Column('example', sa.String(length=300), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_description', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('psychology', sa.JSON(), nullable=False),
    sa.Column('offer_types', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('content_types', sa.JSON(), nullable=False),
    sa.Column('typical_duration', sa.String(length=100), nullable=False),
    sa.Column('budget_notes', sa.Text(), nullable=False),
    sa.Column('success_metrics', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['campaign_strategy_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_strategy_types_family_id'), 'campaign_strategy_types', ['family_id'], unique=False)
    op.create_index(op.f('ix_campaign_strategy_types_key'), 'campaign_strategy_types', ['key'], unique=True)
    op.create_table('competitors',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('social_handles', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_brand_id'), 'competitors', ['brand_id'], unique=False)
    op.create_table('defense_playbooks',
    sa.Column('brand_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('recommended_strategy_key', sa.String(length=60), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defense_playbooks_brand_id'), 'defense_playbooks', ['brand_id'], unique=False)
    op.create_index(op.f('ix_defense_playbooks_event_type'), 'defense_playbooks', ['event_type'], unique=False)
    op.create_table('competitor_events',
    sa.Column('competitor_id', sa.String(length=32), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_events_brand_id'), 'competitor_events', ['brand_id'], unique=False)
    op.create_index(op.f('ix_competitor_events_competitor_id'), 'competitor_events', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_events_status'), 'competitor_events', ['status'], unique=False)
    # SQLite can't ALTER a table to add a foreign key constraint directly — batch
    # mode recreates the table under the hood (copy-and-move), which is required
    # here even though the equivalent ops on other dialects would be plain add_column.
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_type_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('triggered_by_event_id', sa.String(length=32), nullable=True))
        batch_op.create_index(op.f('ix_campaigns_strategy_type_id'), ['strategy_type_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_campaigns_triggered_by_event_id', 'competitor_events', ['triggered_by_event_id'], ['id'], ondelete='SET NULL'
        )
        batch_op.create_foreign_key(
            'fk_campaigns_strategy_type_id', 'campaign_strategy_types', ['strategy_type_id'], ['id'], ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_campaigns_strategy_type_id', type_='foreignkey')
        batch_op.drop_constraint('fk_campaigns_triggered_by_event_id', type_='foreignkey')
        batch_op.drop_index(op.f('ix_campaigns_strategy_type_id'))
        batch_op.drop_column('triggered_by_event_id')
        batch_op.drop_column('strategy_type_id')
    op.drop_index(op.f('ix_competitor_events_status'), table_name='competitor_events')
    op.drop_index(op.f('ix_competitor_events_competitor_id'), table_name='competitor_events')
    op.drop_index(op.f('ix_competitor_events_brand_id'), table_name='competitor_events')
    op.drop_table('competitor_events')
    op.drop_index(op.f('ix_defense_playbooks_event_type'), table_name='defense_playbooks')
    op.drop_index(op.f('ix_defense_playbooks_brand_id'), table_name='defense_playbooks')
    op.drop_table('defense_playbooks')
    op.drop_index(op.f('ix_competitors_brand_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_campaign_strategy_types_key'), table_name='campaign_strategy_types')
    op.drop_index(op.f('ix_campaign_strategy_types_family_id'), table_name='campaign_strategy_types')
    op.drop_table('campaign_strategy_types')
    op.drop_index(op.f('ix_campaign_strategy_families_key'), table_name='campaign_strategy_families')
    op.drop_table('campaign_strategy_families')
    # ### end Alembic commands ###
