"""initial schema

Revision ID: ba2d83aa362d
Revises: 
Create Date: 2026-09-06 04:16:44.295500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2d83aa362d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_campaign_id'), 'ai_usage', ['campaign_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('voice', sa.Text(), nullable=False),
    sa.Column('language_rules', sa.JSON(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('typography', sa.JSON(), nullable=False),
    sa.Column('spacing', sa.JSON(), nullable=False),
    sa.Column('visual_style', sa.JSON(), nullable=False),
    sa.Column('forbidden_styles', sa.JSON(), nullable=False),
    sa.Column('preferred_ctas', sa.JSON(), nullable=False),
    sa.Column('disallowed_terms', sa.JSON(), nullable=False),
    sa.Column('disclaimers', sa.JSON(), nullable=False),
    sa.Column('target_audiences', sa.JSON(), nullable=False),
    sa.Column('target_countries', sa.JSON(), nullable=False),
    sa.Column('social_handles', sa.JSON(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('campaign_rules', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('jobs',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=200), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('job_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_campaign_id'), 'jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_purpose'), 'prompt_versions', ['purpose'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('brand_assets',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_assets_brand_id'), 'brand_assets', ['brand_id'], unique=False)
    op.create_table('campaign_sequences',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('category_slug', sa.String(length=200), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'category_slug', name='uq_seq_brand_category')
    )
    op.create_index(op.f('ix_campaign_sequences_brand_id'), 'campaign_sequences', ['brand_id'], unique=False)
    op.create_table('categories',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('parent_category_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_brand_id'), 'categories', ['brand_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.create_table('performance_insights',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('supporting_campaign_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_insights_brand_id'), 'performance_insights', ['brand_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region_city', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('estimated_relevance', sa.Float(), nullable=False),
    sa.Column('audience_size', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('joined_status', sa.String(length=30), nullable=False),
    sa.Column('promo_allowed', sa.Boolean(), nullable=True),
    sa.Column('posting_rules', sa.Text(), nullable=False),
    sa.Column('recommended_content_style', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_brand_id'), 'opportunities', ['brand_id'], unique=False)
    op.create_table('products',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_table('assets',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('absolute_path', sa.String(length=2000), nullable=False),
    sa.Column('relative_path', sa.String(length=2000), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.Float(), nullable=False),
    sa.Column('created_at_fs', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at_fs', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_role', sa.String(length=30), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=False),
    sa.Column('ai_metadata', sa.JSON(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=False),
    sa.Column('checksum_stale', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('absolute_path', name='uq_assets_absolute_path')
    )
    op.create_index(op.f('ix_assets_absolute_path'), 'assets', ['absolute_path'], unique=False)
    op.create_index(op.f('ix_assets_brand_id'), 'assets', ['brand_id'], unique=False)
    op.create_index(op.f('ix_assets_category_id'), 'assets', ['category_id'], unique=False)
    op.create_index(op.f('ix_assets_phash'), 'assets', ['phash'], unique=False)
    op.create_index(op.f('ix_assets_product_id'), 'assets', ['product_id'], unique=False)
    op.create_index(op.f('ix_assets_sha256'), 'assets', ['sha256'], unique=False)
    op.create_table('research_runs',
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('query_context', sa.JSON(), nullable=False),
    sa.Column('ttl_kind', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_runs_brand_id'), 'research_runs', ['brand_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('display_id', sa.String(length=100), nullable=False),
    sa.Column('brand_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=True),
    sa.Column('objective', sa.String(length=30), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('funnel_stage', sa.String(length=30), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('angle', sa.String(length=100), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('main_promise', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=False),
    sa.Column('campaign_family', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('research_run_id', sa.String(length=32), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_campaigns_display_id'), 'campaigns', ['display_id'], unique=True)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('research_insights',
    sa.Column('research_run_id', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('freshness', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('recommended_implication', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_insights_research_run_id'), 'research_insights', ['research_run_id'], unique=False)
    op.create_table('research_sources',
    sa.Column('research_run_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('source_title', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_research_run_id'), 'research_sources', ['research_run_id'], unique=False)
    op.create_table('campaign_assets',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_assets_asset_id'), 'campaign_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_campaign_assets_campaign_id'), 'campaign_assets', ['campaign_id'], unique=False)
    op.create_table('campaign_fingerprints',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('text_embedding', sa.JSON(), nullable=True),
    sa.Column('angle', sa.String(length=100), nullable=False),
    sa.Column('promise_summary', sa.Text(), nullable=False),
    sa.Column('objective', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('asset_sha256_list', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_fingerprints_campaign_id'), 'campaign_fingerprints', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_campaign_fingerprints_text_hash'), 'campaign_fingerprints', ['text_hash'], unique=False)
    op.create_table('campaign_opportunities',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.String(length=32), nullable=False),
    sa.Column('community_post_text', sa.Text(), nullable=False),
    sa.Column('posted', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_opportunities_campaign_id'), 'campaign_opportunities', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_opportunities_opportunity_id'), 'campaign_opportunities', ['opportunity_id'], unique=False)
    op.create_table('campaign_outputs',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_outputs_campaign_id'), 'campaign_outputs', ['campaign_id'], unique=False)
    op.create_table('campaign_slides',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('eyebrow', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.String(length=300), nullable=False),
    sa.Column('visual_brief', sa.Text(), nullable=False),
    sa.Column('source_asset_id', sa.String(length=32), nullable=True),
    sa.Column('generated_background_path', sa.String(length=2000), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('rendered_asset_path', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_slides_campaign_id'), 'campaign_slides', ['campaign_id'], unique=False)
    op.create_table('campaign_variants',
    sa.Column('parent_campaign_id', sa.String(length=32), nullable=False),
    sa.Column('variant_campaign_id', sa.String(length=32), nullable=False),
    sa.Column('varies', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_variants_parent_campaign_id'), 'campaign_variants', ['parent_campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_variants_variant_campaign_id'), 'campaign_variants', ['variant_campaign_id'], unique=False)
    op.create_table('publications',
    sa.Column('campaign_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_post_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_campaign_id'), 'publications', ['campaign_id'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('publication_id', sa.String(length=32), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('leads', sa.Integer(), nullable=False),
    sa.Column('bookings', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_publication_id'), 'performance_metrics', ['publication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_metrics_publication_id'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_publications_campaign_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_campaign_variants_variant_campaign_id'), table_name='campaign_variants')
    op.drop_index(op.f('ix_campaign_variants_parent_campaign_id'), table_name='campaign_variants')
    op.drop_table('campaign_variants')
    op.drop_index(op.f('ix_campaign_slides_campaign_id'), table_name='campaign_slides')
    op.drop_table('campaign_slides')
    op.drop_index(op.f('ix_campaign_outputs_campaign_id'), table_name='campaign_outputs')
    op.drop_table('campaign_outputs')
    op.drop_index(op.f('ix_campaign_opportunities_opportunity_id'), table_name='campaign_opportunities')
    op.drop_index(op.f('ix_campaign_opportunities_campaign_id'), table_name='campaign_opportunities')
    op.drop_table('campaign_opportunities')
    op.drop_index(op.f('ix_campaign_fingerprints_text_hash'), table_name='campaign_fingerprints')
    op.drop_index(op.f('ix_campaign_fingerprints_campaign_id'), table_name='campaign_fingerprints')
    op.drop_table('campaign_fingerprints')
    op.drop_index(op.f('ix_campaign_assets_campaign_id'), table_name='campaign_assets')
    op.drop_index(op.f('ix_campaign_assets_asset_id'), table_name='campaign_assets')
    op.drop_table('campaign_assets')
    op.drop_index(op.f('ix_research_sources_research_run_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_insights_research_run_id'), table_name='research_insights')
    op.drop_table('research_insights')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_display_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_research_runs_brand_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index(op.f('ix_assets_sha256'), table_name='assets')
    op.drop_index(op.f('ix_assets_product_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_phash'), table_name='assets')
    op.drop_index(op.f('ix_assets_category_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_brand_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_absolute_path'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_opportunities_brand_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_performance_insights_brand_id'), table_name='performance_insights')
    op.drop_table('performance_insights')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_brand_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_campaign_sequences_brand_id'), table_name='campaign_sequences')
    op.drop_table('campaign_sequences')
    op.drop_index(op.f('ix_brand_assets_brand_id'), table_name='brand_assets')
    op.drop_table('brand_assets')
    op.drop_table('settings')
    op.drop_index(op.f('ix_prompt_versions_purpose'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_campaign_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_ai_usage_campaign_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
